#!/usr/bin/env python3
"""Make a tiny original/public-domain 65C816 test program (no game ROM inputs)."""
from pathlib import Path
code=[]
def emit(*values): code.extend(values)
def setreg(address,value): emit(0xA9,value,0x8D,address&255,address>>8)
def loadlong(address,dest): emit(0xAF,address&255,(address>>8)&255,address>>16,0x8D,dest&255,dest>>8)
def readreg(address,dest): emit(0xAD,address&255,address>>8,0x8D,dest&255,dest>>8)
# Reset enters emulation/8-bit mode. Enable local RAM writes and IRQ/NMI.
emit(0x78,0xD8)
for address,value in [(0x222A,0xFF),(0x220A,0x90),(0x2210,0x80),(0x2227,0x80)]: setreg(address,value)
emit(0x58)
# CFFFFF / D00000 cross a bank-register window. Repeat the exact D00000 read.
for a,d in [(0xCFFFFF,0x100),(0xD00000,0x101),(0xD00000,0x102),(0xE00001,0x103)]: loadlong(a,d)
# ROM to IRAM, source crosses a 512-word SDRAM row and a 64 KiB CPU bank.
for address,value in [(0x2230,0xC0),(0x2232,0xFD),(0x2233,0xFF),(0x2234,0xC1),
                      (0x2238,7),(0x2239,0),(0x2235,8),(0x2236,1)]: setreg(address,value)
# VBP preload, odd byte address, cross word+bank, and automatic 16-bit advance.
for address,value in [(0x2258,0x80),(0x2259,0xFF),(0x225A,0xFF),(0x225B,0xC2)]: setreg(address,value)
for a,d in [(0x230C,0x120),(0x230D,0x121),(0x230C,0x122),(0x230D,0x123)]: readreg(a,d)
# ROM to BWRAM, another bank-window boundary.
for address,value in [(0x2230,0xC4),(0x2232,0xFD),(0x2233,0xFF),(0x2234,0xDF),
                      (0x2238,7),(0x2239,0),(0x2235,0x20),(0x2236,0),(0x2237,0)]: setreg(address,value)
setreg(0x2209,0x50)  # SNES local NMI/IRQ vector substitution
setreg(0x13F,0xA5)
emit(0xCB,0x80,0xFD)  # WAI/BRA WAI
rom=dict(enumerate(code))
for base,dest,ack in [(0x1000,0x130,0x80),(0x1100,0x131,0x10)]:
    routine=[0x48,0xEE,dest&255,dest>>8,0xA9,ack,0x8D,0x0B,0x22,0x68,0x40]
    rom.update({base+i:b for i,b in enumerate(routine)})
text='''-- Generated by make_sa1_test_program.py; original synthetic test software.
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
package sa1_test_program is
    function rom_byte(address : natural) return std_logic_vector;
    function rom_word(address : natural) return std_logic_vector;
end package;
package body sa1_test_program is
    function rom_byte(address : natural) return std_logic_vector is
        variable a, b : unsigned(31 downto 0);
    begin
        case address is
'''
text+=''.join(f'            when {a} => return x"{b:02X}";\n' for a,b in sorted(rom.items()))
text+='''            when others =>
                a:=to_unsigned(address,32);
                b:=resize(a*37,32) xor shift_right(a,8) xor shift_right(a,16) xor x"0000005A";
                return std_logic_vector(b(7 downto 0));
        end case;
    end function;
    function rom_word(address : natural) return std_logic_vector is
        variable aligned : natural;
    begin
        aligned:=(address/2)*2;
        return rom_byte(aligned+1) & rom_byte(aligned);
    end function;
end package body;
'''
Path(__file__).with_name('sa1_test_program.vhd').write_text(text)
print(f'{len(code)} program bytes, {len(rom)-len(code)} interrupt bytes')
