#!/usr/bin/env python3
"""Run real SPC7110 decoder + mapper latency regressions (GHDL, Intel models).

No ROM images are used. The sole oracle is the immutable b63f800 arithmetic
implementation with deterministic generated bytes, explicitly NOT game coverage.
"""
import argparse
import collections
import hashlib
import json
import os
from pathlib import Path
import shutil
import subprocess
import tempfile

ROOT = Path(__file__).resolve().parents[1]
DEC = ROOT / 'rtl/upstream/chip/SPC7110'
TEST = ROOT / 'tests/decoder_waits'


def run(cmd, *, ok=True):
    p = subprocess.run([str(c) for c in cmd], capture_output=True, text=True, timeout=120)
    if ok and p.returncode:
        raise RuntimeError(' '.join(map(str, cmd))+'\n'+p.stdout+p.stderr)
    return p


def coverage(path):
    """Check actual rising/falling state conservation from instrumented RTL VCD."""
    scopes, names, values = [], {}, {}
    counts = collections.Counter()
    checks = 0
    in_header = True
    changes = {}
    prefix = 'tb_spc7110_decoder.dut.'
    stable = ['con','top','lps','lps_inv','inverts','lpss','shift','prob_big_half',
              'in_high','in_mid','in_low','in_buf','in_cnt','output','pix_cnt',
              'bit_cnt','bit_cnt_last','load','trace_state']
    def finish():
        nonlocal checks
        if not changes:
            return
        old = values.copy()
        values.update(changes)
        changes.clear()
        def val(name, previous=False):
            return (old if previous else values).get(names[prefix+name])
        if val('rst_n', True) != '1' or val('init', True) != '0':
            return
        rising = val('clk',True)=='0' and val('clk')=='1'
        falling = val('clk',True)=='1' and val('clk')=='0'
        blocked = rising and (val('enable',True)=='0' or
                   (val('int_rd',True)=='1' and val('di_valid',True)=='0'))
        half_blocked = falling and val('half_step',True)=='0'
        if blocked or half_blocked:
            state = int(val('trace_state',True), 2)
            category = 'input_empty' if rising and val('enable',True)=='1' else 'enable_pause' if rising else 'held_falling_half'
            counts[f'{category}_state{state}'] += 1
            for key in stable:
                assert val(key,True)==val(key), f'{key} changed during {category} in state{state}'
            checks += len(stable)
    for line in path.read_text().splitlines():
        words=line.split()
        if in_header:
            if line.startswith('$scope'): scopes.append(words[2])
            elif line.startswith('$upscope'): scopes.pop()
            elif line.startswith('$var'):
                names['.'.join(scopes+[words[4].split('[')[0]])]=words[3]
            elif line.startswith('$enddefinitions'): in_header=False
        elif line.startswith('#'):
            finish()
        elif line.startswith('b'):
            value, ident=line[1:].split(); changes[ident]=value
        elif line and line[0] in '01xXzZ': changes[line[1:]]=line[0]
    finish()
    for state in (1,2,3):
        assert counts[f'input_empty_state{state}']>0, f'No empty stall in active state{state}'
    assert counts['held_falling_half_state3']>0
    return {'counts': dict(counts), 'state_hold_assertions': checks}


def main():
    ap=argparse.ArgumentParser(description=__doc__)
    ap.add_argument('--ghdl',default=shutil.which('ghdl') or '/tmp/msu1-tools/bin/ghdl')
    ap.add_argument('--vendor-sim-dir',type=Path,default=Path(os.environ.get('QUARTUS_SIM_LIB', ROOT.parent/'toolchain/intelFPGA_lite/21.1/quartus/eda/sim_lib')))
    ap.add_argument('--bridge',type=Path)
    ap.add_argument('--quick',action='store_true')
    ap.add_argument('--output',type=Path)
    args=ap.parse_args()
    baseline=(TEST/'spc7110_dec_baseline.vhd').read_text()
    normalized=baseline.split('\n',1)[1].replace('SPC7110_DEC_BASELINE','SPC7110_DEC')
    original=run(['git','-C',ROOT,'show','b63f800:rtl/upstream/chip/SPC7110/SPC7110_DEC.vhd']).stdout
    assert normalized==original, 'Immutable baseline changed'
    results={'baseline_sha256':hashlib.sha256(original.encode()).hexdigest(), 'decoder':[], 'mapper':[], 'mutations':[], 'coverage':{}}
    with tempfile.TemporaryDirectory(prefix='spc7110-waits-') as tmp:
        tmp=Path(tmp)
        work=tmp/'work';work.mkdir()
        opts=['--std=08','-fsynopsys',f'--workdir={work}']
        def analyze(files): return run([args.ghdl,'-a',*opts,*files])
        def simulate(tb,*flags,ok=True): return run([args.ghdl,'-r',*opts,tb,*flags,'--assert-level=error','--ieee-asserts=disable-at-0'],ok=ok)
        decoder=(DEC/'SPC7110_DEC.vhd').read_text()
        # Diagnostic enum encoding only; no behavior changes to tested RTL.
        instrumented=decoder.replace('signal HALF_STEP : std_logic;', 'signal HALF_STEP : std_logic;\n signal TRACE_STATE : unsigned(1 downto 0);')
        instrumented=instrumented.replace('begin\n\t\n\tprocess(', "begin\n TRACE_STATE <= to_unsigned(DecompStates_t'pos(DCS),2);\n\tprocess(",1)
        trace=tmp/'spc7110_trace.vhd';trace.write_text(instrumented)
        analyze([DEC/'SPC7110_DEC_PKG.vhd',trace,TEST/'spc7110_dec_baseline.vhd',TEST/'tb_spc7110_decoder.vhd'])
        seeds=(1,) if args.quick else (1,19,877)
        for mode in range(3):
            for seed in seeds:
                vcd=tmp/'coverage.vcd'
                p=simulate('tb_spc7110_decoder',f'-gMODE_ID={mode}',f'-gSEED={seed}',f'--vcd={vcd}')
                row=next(l.split('SPC7110 PASS ')[1] for l in p.stdout.splitlines() if 'SPC7110 PASS' in l)
                results['decoder'].append(dict(x.split('=') for x in row.split()))
                results['coverage'][f'{mode}/{seed}']=coverage(vcd)
                print(row,flush=True)
        mutations={
          'accept_invalid_input':("INIT = '1' or INT_RD = '0' or DI_VALID = '1'", "INIT = '1' or INT_RD = '0' or true"),
          'advance_unowned_falling_half':("if HALF_STEP = '1' then", 'if true then'),
          'pop_without_valid':('RD <= INT_RD and DI_VALID and ENABLE and not INIT;', 'RD <= INT_RD and ENABLE and not INIT;'),
          'ignore_enable':("if ENABLE = '1' then", 'if true then'),
        }
        for name,(old,new) in mutations.items():
            assert decoder.count(old)==1, (name,decoder.count(old))
            mutant=tmp/f'{name}.vhd';mutant.write_text(decoder.replace(old,new))
            analyze([mutant,TEST/'tb_spc7110_decoder.vhd'])
            p=simulate('tb_spc7110_decoder',ok=False)
            assert p.returncode!=0, f'Mutation survived: {name}'
            failure=next(l for l in (p.stdout+p.stderr).splitlines() if 'failure' in l)
            results['mutations'].append({'name':name,'detected':True,'failure':failure})
            print('mutation rejected:',name,flush=True)
        analyze([DEC/'SPC7110_DEC.vhd'])
        for lib,files in [('lpm',['220pack.vhd','220model.vhd']),('altera_mf',['altera_mf_components.vhd','altera_mf.vhd'])]:
            out=tmp/lib;out.mkdir()
            run([args.ghdl,'-a','--std=08','-fsynopsys',f'--work={lib}',f'--workdir={out}',*[args.vendor_sim_dir/f for f in files]])
            opts.append(f'-P{out}')
        bridge=args.bridge or ROOT/'rtl/upstream/chip/SA1/SA1RomBridge.vhd'
        if not bridge.exists():
            bridge=tmp/'SA1RomBridge.vhd'
            bridge.write_text(run(['git','-C',ROOT,'show','116961d:rtl/upstream/chip/SA1/SA1RomBridge.vhd']).stdout)
        analyze([bridge,ROOT/'rtl/upstream/chip/RTC4513.vhd',DEC/'SPC7110_FIFO.vhd',DEC/'SPC7110_MULDIV.vhd',DEC/'SPC7110.vhd',DEC/'SPC7110Map.vhd',TEST/'tb_spc7110_mapper.vhd'])
        for mode in range(3):
            for delay in ((211,) if args.quick else (1,211,877)):
                p=simulate('tb_spc7110_mapper',f'-gMODE_ID={mode}',f'-gDELAY_MAX={delay}')
                row=next(l.split('SPC mapper PASS ')[1] for l in p.stdout.splitlines() if 'SPC mapper PASS' in l)
                data=dict(x.split('=') for x in row.split());data['delay_max']=delay
                results['mapper'].append(data);print(row+f' delay_max={delay}',flush=True)
        results['offset_mapper']=[]
        for mode in range(3):
            for offset in (1,9):
                p=simulate('tb_spc7110_mapper',f'-gMODE_ID={mode}',f'-gOFFSET_WORDS={offset}','-gDELAY_MAX=877')
                row=next(l.split('SPC mapper PASS ')[1] for l in p.stdout.splitlines() if 'SPC mapper PASS' in l)
                data=dict(x.split('=') for x in row.split());data['offset_words']=offset
                results['offset_mapper'].append(data);print(row+f' offset_words={offset}',flush=True)
        core=(DEC/'SPC7110.vhd').read_text()
        mapper=(DEC/'SPC7110Map.vhd').read_text()
        integration_mutations=[
          ('ignore_fifo_empty', 'core', 'DI_VALID => not FIFO_EMPTY,', "DI_VALID => '1',"),
          ('retire_missing_decoded_byte', 'core', "PORT_WAIT <= '1' when ROM_HANDSHAKE and", "PORT_WAIT <= '1' when false and"),
          ('fabricate_drom_completion', 'mapper', 'SPC7110_DROM_RDY <= MEM_READY(1);', "SPC7110_DROM_RDY <= '1';"),
        ]
        for name,kind,old,new in integration_mutations:
            text=core if kind=='core' else mapper
            assert text.count(old)==1, (name,text.count(old))
            mutant=tmp/f'{name}.vhd';mutant.write_text(text.replace(old,new))
            analyze([mutant]+([DEC/'SPC7110Map.vhd'] if kind=='core' else [])+[TEST/'tb_spc7110_mapper.vhd'])
            p=simulate('tb_spc7110_mapper',ok=False)
            assert p.returncode!=0, f'Mutation survived: {name}'
            failure=next(l for l in (p.stdout+p.stderr).splitlines() if 'failure' in l)
            results['mutations'].append({'name':name,'detected':True,'failure':failure})
            print('mutation rejected:',name,flush=True)
            analyze([DEC/'SPC7110.vhd',DEC/'SPC7110Map.vhd',TEST/'tb_spc7110_mapper.vhd'])
        for name,old,new,offset in [
          ('retain_reclaimed_bank', "if DEC_RESUME='1' then", 'if false then', 9),
          ('parity_only_offset_resume', "(ROM_HANDSHAKE and DEC_VALID(to_integer(DEC_BUF_RD_ADDR))='0')", '(false)', 9),
        ]:
            assert core.count(old)==1
            mutant=tmp/f'{name}.vhd';mutant.write_text(core.replace(old,new))
            analyze([mutant,DEC/'SPC7110Map.vhd',TEST/'tb_spc7110_mapper.vhd'])
            p=simulate('tb_spc7110_mapper',f'-gOFFSET_WORDS={offset}','-gDELAY_MAX=877',ok=False)
            assert p.returncode!=0, f'Mutation survived: {name}'
            failure=next(l for l in (p.stdout+p.stderr).splitlines() if 'failure' in l)
            results['mutations'].append({'name':name,'detected':True,'failure':failure})
            print('mutation rejected:',name,flush=True)
            analyze([DEC/'SPC7110.vhd',DEC/'SPC7110Map.vhd',TEST/'tb_spc7110_mapper.vhd'])
        # Compile both mapper configurations; legacy timing is not the variable-
        # latency transport test and remains separately labeled.
        run([args.ghdl,'-e',*opts,'SPC7110Map'])
    if args.output:
        args.output.parent.mkdir(parents=True,exist_ok=True)
        args.output.write_text(json.dumps(results,indent=2)+'\n')
    print('SPC7110 wait regression PASS')

if __name__=='__main__': main()
