pll_reconfig_sim/pll_reconfig.v
pll_reconfig_sim/altera_pll_reconfig/altera_pll_reconfig_top.v
pll_reconfig_sim/altera_pll_reconfig/altera_pll_reconfig_mif_reader.v
pll_reconfig_sim/altera_pll_reconfig/altera_pll_reconfig_core.v
pll_reconfig_sim/altera_pll_reconfig/altera_std_synchronizer.v
